---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: cloud-native-cap-xsuaa
spec:
  clusterServiceClassExternalName: xsuaa
  clusterServicePlanExternalName: application
  # xs security json to yaml
  parameters:
    xsappname: cloud-native-cap
    tenant-mode: dedicated
    scopes:
      - description: scope allow user read houses
        name: $XSAPPNAME.READ_HOUSE
      - description: scope allow user write houses
        name: $XSAPPNAME.WRITE_HOUSE
    role-templates:
      - name: HOUSE_VIEWER
        scope-references:
          - $XSAPPNAME.READ_HOUSE
      - name: HOUSE_ADMIN
        scope-references:
          - $XSAPPNAME.READ_HOUSE
          - $XSAPPNAME.WRITE_HOUSE
status:
  spec:
  instanceRef:
    name: cloud-native-cap-xsuaa
  secretName: cloud-native-cap-xsuaa-secrets

---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: cloud-native-cap-xsuaa-secrets
---
apiVersion: servicecatalog.kyma-project.io/v1alpha1
kind: ServiceBindingUsage
metadata:
  name: cloud-native-cap-xsuaa-sbu
spec:
  serviceBindingRef:
    name: cloud-native-cap-xsuaa-sb
  usedBy:
    kind: deployment
    name: cloud-native-cap-srv
---
apiVersion: apps/v1
# i prefer to use Job to deploy the contents
# but in the job container
# the deployer can not connect to target HANA db
# use Deployment as a walk around
kind: Deployment
metadata:
  labels:
    com.sap.k8s.app: cloud-native-cap-hdi-container-deploy
  name: cloud-native-cap-hdi-container-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      com.sap.k8s.app: "cloud-native-cap-hdi-container-deploy"
  template:
    metadata:
      labels:
        com.sap.k8s.app: cloud-native-cap-hdi-container-deploy
    spec:
      containers:
        - name: cloud-native-cap-hdi-container-v
          image: quay.io/cloud-native-public/cloud-native-cap-db:0.0.1
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "0.5"
              memory: "500Mi"
          volumeMounts:
            - name: cloud-native-cap-hdi-container-v
              mountPath: "/etc/secrets/sapcp/hana/hdi-container"
              readOnly: true
      volumes:
        - name: cloud-native-cap-hdi-container-v
          secret:
            secretName: cloud-native-cap-hdi-container
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    com.sap.k8s.app: cloud-native-cap-srv
  name: cloud-native-cap-srv
spec:
  replicas: 1
  selector:
    matchLabels:
      com.sap.k8s.app: cloud-native-cap-srv
  strategy: {}
  template:
    metadata:
      labels:
        com.sap.k8s.app: cloud-native-cap-srv
    spec:
      containers:
        - image: quay.io/cloud-native-public/cloud-native-cap-srv:0.0.1
          imagePullPolicy: Always
          name: cloud-native-cap-srv
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "0.1"
              memory: "500Mi"
          volumeMounts:
            - name: cloud-native-cap-hdi-container-v
              mountPath: "/etc/secrets/sapcp/hana/hdi-container"
              readOnly: true
            - name: cloud-native-cap-xsuaa-secrets-v
              mountPath: "/etc/secrets/sapcp/xsuaa/cloud-native-cap-xsuaa"
              readOnly: true
      volumes:
        - name: cloud-native-cap-hdi-container-v
          secret:
            secretName: cloud-native-cap-hdi-container
        - name: cloud-native-cap-xsuaa-secrets-v
          secret:
            secretName: cloud-native-cap-xsuaa-secrets
      restartPolicy: Always
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: cloud-native-cap-srv-hps
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cloud-native-cap-srv
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: v1
kind: Service
metadata:
  labels:
    com.sap.k8s.app: rsshub
  name: cloud-native-cap-service
spec:
  ports:
    - name: web
      port: 8080
      targetPort: 8080
  selector:
    com.sap.k8s.app: cloud-native-cap-srv
---
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  generation: 1
  name: cloud-native-cap-api-rule
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - accessStrategies:
        - config: {}
          handler: allow
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - HEAD
      path: /.*
  service:
    host: cloud-native-cap
    name: cloud-native-cap-service # please remember this is 'SERVICE' resource name
    port: 8080
